### ISSUE TITLE
Support for data that cross international dateline?

### ISSUE THREAD

**Issue by abfleishman** [benjamin-merkel/ProMM#1]
I am hoping to use your package for birds that cross the international dateline during migration. I seem to be getting issues with the boundary.box in the `prob_algorithm`. Is your code set up to do that?  If not, do you have suggestions so i can move forward?

**Comment by benjamin-merkel** [comment]
That is a very good point. I have not thought about it as I work in the Atlantic. Thank you very much for pointing this out. I put it on my update list and will get to it as soon as possible. Would you have a short data piece crossing the dateline for me so I can try it out?

**Comment by abfleishman** [comment]
What is a "short data piece" for you? and in which format?

**Comment by benjamin-merkel** [comment]
A week long should be enough, but basically as much as you feel comfortable sharing. Easiest would be to get the light, submersion and temperature file.

**Comment by benjamin-merkel** [comment]
So, I run the code on you bird crossing the dateline with a boundary box of c(-180, 180, 0, 90) and it seemed to work without problem (albeit slow due to the wide range). I will adopt the script to make it possible to narrow down the bounadry box for the pacific.

![output](https://cloud.githubusercontent.com/assets/11088303/21539935/c50cc49e-cdab-11e6-9afe-787fa554a1ed.png)

**Comment by abfleishman** [comment]
Yes I have had success now doing the same bounding box. But I thought it might be more efficient with a smaller box

**Comment by benjamin-merkel** [comment]
try it again. I added a functionality to wrap the boundary box around the dateline. Syntax should be to have the western boundary and than the eastern boundary followed by the southern and the northern edge. However, at the moment it should be in the -180 to 180 convention (e.g. for your case it would be something like c(140,-160,20,90) ). Also, I think I found the bug giving you your error message from earlier.

**Comment by abfleishman** [comment]
Great! I will try it tonight!

**Comment by abfleishman** [comment]
I am now getting a warning hundreds of times when I run `prob_algorithm`
 `NOTE: rgdal::checkCRSArgs: no proj_defs.dat in PROJ.4 shared files`

I have tried to understand why and it seems that I have an older version of PROJ on my computer but I can't seem to update it.  I am not sure why I might be getting this error now but I thought I would ask you about it?

**Comment by AndreasRavache** [comment]
Hello Benjamin, I have similar problems, each time I try to run the prob_algorithm() function, I get this error message:
Error in .pointsToMatrix(p1) : 
  Points are projected. They should be in degrees (longitude/latitude)

I don't know if you are still active here, but coul you help me please?

**Comment by benjamin-merkel** [comment]
Hi Andreas, 
does this mean you try to run data over the date line or the 180 Longitude? when does this error occur? I have not encountered it yet.

Cheers
ben

**Comment by lkitch** [comment]
Hello,

I am working on measuring the distance between two points using their Lat, Long. This is the closest thread I can find to that. The error message is:

 Error in .pointsToMatrix(p1) : latitude < -90. 
 
 Any Idea how I can solve this?

**Comment by benjamin-merkel** [comment]
There are quite a few packages and functions out there that can measure distance in lat-long. This package also just uses these functions from other works. You are getting this error most likely because your are providing latitudes lower than -90 and hence outside the range. Check your data for errors and your function input as well. Maybe you switched lon and lat?

**Comment by lkitch** [comment]
@benjamin-merkel I worked it some more and the lat and long are reversed in R. point2<- c(121.4944,38.5816)
