### ISSUE TITLE
R 4 compatibility

### ISSUE THREAD

**Issue by bloopery** [benjamin-merkel/ProMM#10]
Hi Benjamin and thank you for this package - I have been using it successfully in R v3.6, but I am unable to install it after upgrading to R v4.0.2. 

`devtools::install_github("benjamin-merkel/probGLS") `

yields this: 

```
Downloading GitHub repo benjamin-merkel/probGLS@HEAD
√  checking for file 'C:\Users\bloopery\AppData\Local\Temp\RtmpUZiAgx\remotes2d984a426693\benjamin-merkel-probGLS-b3808f6/DESCRIPTION' ...
-  preparing 'probGLS':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'probGLS_0.9.5.tar.gz'
   
Installing package into ‘C:/Users/bloopery/Documents/r/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'probGLS' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'raster' was built under R version 4.0.3
Execution halted
ERROR: lazy loading failed for package 'probGLS'
* removing 'C:/Users/bloopery/Documents/r/win-library/4.0/probGLS'
Error: Failed to install 'probGLS' from GitHub:
  (converted from warning) installation of package ‘C:/Users/bloopery/AppData/Local/Temp/RtmpUZiAgx/file2d98183952a0/probGLS_0.9.5.tar.gz’ had non-zero exit status
```

Is this to be expected (the package isn't compatible with newer R releases) or should I be doing something differently?

**Comment by benjamin-merkel** [comment]
Hi,

sorry for the late answer. I did not see your message before now. At the top of my head I guess it has to do with the recent switch from PROJ.4 to PROJ.6 and the fallout this created in all spatial packages. Have you tried to install raster first and then probGLS as you error appeared when installing raster?

Cheers,
ben

**Comment by bloopery** [comment]
Thank you for your help, that solved it. I had to update R to v4.0.3, reinstall raster, then probGLS.
Have a nice day!
