### ISSUE TITLE
Make prob_algorithm work without activity data

### ISSUE THREAD

**Issue by CLambert1** [benjamin-merkel/ProMM#11]
Hi Ben,
I was expecting using prob_algorithm function to correct locations estimated from an old GLS dataset where loggers only recorded light levels and temperatures, as it is stated that the function should consider a dry state for all points if act = NULL. However, as it stands now, the existence of an act dataframe in the environment is mandatory for the function to work (from what I understand of the code it is used to derive distance from previous location, l403). Would it be possible for the algorithm to work without activity data?
Also, the land mask netcdf had its name changed in the NOAA repository (https://downloads.psl.noaa.gov/Datasets/noaa.oisst.v2.highres/lsmask.oisst.nc) which makes the automatic downloading fail. 
Regards,
Charlotte

**Comment by benjamin-merkel** [comment]
Hi Charlotte,
I have updated the land mask link. Thank you for catching that.
Regarding the activity data, you can just give the algorithm a simple input file that is just always dry. This way the algorithm will always assume the dry speed distribution. I will add functionality to make this input optional when i get around doing it, but until than i hope this work around will be sufficient.

Cheers,
ben

**Comment by CLambert1** [comment]
Hi, the work around seems to work well indeed! Thanks ;)
Best
Charlotte
