### ISSUE TITLE
BAS tags without SST sensors

### ISSUE THREAD

**Issue by autumnlynn** [benjamin-merkel/ProMM#2]
Thanks very much for this new tool. I have BAS data from tags without sst sensors. I've previously used a kalman filter to process these, and would like to compare to your results. However, it seems that sst is required in the current framework. Is that correct, or is there an easy way to omit? Cheers, Autumn-Lynn

**Comment by benjamin-merkel** [comment]
SST can be omit from being used by setting sensor=NULL. However, at the moment it is still required to have the landmask file (a bug I did not realized was there until recently. Will get to it as soon as possible). However, without SST as weighting factor, the results might not be instructive as most likely all you will do is to run a speed filter (and if it is a bird it will be fast). Does this make sense?
