### ISSUE TITLE
error:   object 'newt2' not found`

### ISSUE THREAD

**Issue by abfleishman** [benjamin-merkel/ProMM#3]
I was able to run prob_algorithm() without too much trouble until today. I am now getting this error and can't seem to fix it.  Thoughts?I get the error using my own data and settings, and I just tried to run it for the example data set on the wiki with the code copied from the wiki directly and I get the same error either way.

`Error in prob_algorithm(particle.number = 1000, iteration.number = 50,  : 
  object 'newt2' not found`

Also, the parameter: `range.sun.elev` seems to no longer be a parameter in the function yet it is still in the wiki example.

**Comment by benjamin-merkel** [comment]
Thanks for pointing out the error in the wiki. 
Do you use the latest version of the function? I updated the code a week ago.

**Comment by abfleishman** [comment]
Yes I was using the most up to date version of the code. I have since rolled back to an older version that has been working. I am not sure what information you might Ned to recreate the error but let me know how I can help?
