### ISSUE TITLE
meta <- read_excel('meta.xlsx')

### ISSUE THREAD

**Issue by Thagua** [benjamin-merkel/ProMM#4]
Hi Benjamin,
I am trying to use your code for analyzing geolocator data retrieved from a plover species that lives in the Andean range, in a kind of canyon environment. We get unrealistic results using GeoLight and IntiProc, most of the locations were in the middle of the Atlantic Ocean! (haha).
Sorry, I am sure it's me, but I can't find the "meta.xlsx" file. Is that from NOAA? Could you help me with that, please?
Best wishes

**Comment by benjamin-merkel** [comment]
Hi,
that piece of code related to the specific data used for the method assessement. So, it is a pointer to the meta data in the example (aka start and end dates as well as ids). Best, use the example code given in the function prob_algorithm.
Let me know if I can help further.

**Comment by Thagua** [comment]
Thanks Benjamin.....not used to GitHub presented R packages.
