### ISSUE TITLE
Error in nc_open(fname) : Error in nc_open trying to open file

### ISSUE THREAD

**Issue by jbzwong** [benjamin-merkel/ProMM#6]
Hi Benjamin,
I'm trying to run prob_algorithm() but receive the following error:

184 of 325 steps      Error in R_nc4_open: NetCDF: Unknown file format
Error in nc_open(fname) : 
  Error in nc_open trying to open file...

each time I try to run it. In the function prob_algorithm(), I have specified the NOAA.OI.location as the folder where the NOAA NCDF files are stored: 

NOAA.OI.location = paste0(wd, "/NOAA SST files"))

where the 'NOAA SST files' folder contains 3 files for the SST/sea ice and also the land mask file ('lsmask.oisst.v2.nc').

I have also specified the appropriate years of the NetCDF files that I'm using:

daily.mean.SST <- 'sst.day.mean.2017.nc'
daily.SST.error <- 'sst.day.err.2017.nc'
daily.mean.sea.ice.concentration <- 'icec.day.mean.2017.nc'

When I use the nc_open() function to open the netCDF files independently outside the prob_algorithm() function, it works, so I know the files are in the correct format, but I'm unsure why it's not opening in the function.

When I open the prob_algorithm() function, I think the error may be coming from fname.SST, fname.err, or fname.ice
or 
eoi <- load.NOAA.OISST.V2(
eii <- load.NOAA.OISST.V2(
eri <- load.NOAA.OISST.V2(

Anyways, I'm not sure Is there something I'm missing or a quick fix for it, so I'd appreciate your help!

Thanks!
- Joanna

**Comment by benjamin-merkel** [comment]
Hi Joanna

sorry for the late reply. Have you used the newest probGLS version? In previous versions i hard coded the ".v2" part of each file name which made problems after NOAA changed their naming convention.

Cheers,
Benjamin
