### ISSUE TITLE
no land mask file found

### ISSUE THREAD

**Issue by samidodino** [benjamin-merkel/ProMM#9]
Hi Benjamin! 
I am trying to use your code for analyzing geolocator data retrieved from Magellanic penguin that lives in Argentina and they stay at sea during winter. And I can´t run the prob_algorithm function because I have this error:
"Error: no land mask file found in folder"
And that´s not true, I placed it in the same folder as all the other NetCDF files. Do you have any idea why that happens?
Best

**Comment by benjamin-merkel** [comment]
Hi,

sorry for never answering. I am (apparently) not often checking my github page. Did you manage to resolve your issue?

Cheers,
ben
